config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :workflow_templates

  resources :workflow_template_steps

  resources :company_areas

  resources :documents

  resources :active_workflows

  resources :active_workflow_steps

  resources :roles

  resources :worflow_requests

  resources :messages

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/active_workflow_step.rb
class ActiveWorkflowStep < ActiveRecord::Base
  belongs_to :workflow_template
  belongs_to :active_workflow
end

app/controllers/active_workflow_steps_controller.rb
class ActiveWorkflowStepsController < ApplicationController
  before_action :set_active_workflow_step, only: [:show, :edit, :update, :destroy]

  # GET /active_workflow_steps
  # GET /active_workflow_steps.json
  def index
    @active_workflow_steps = ActiveWorkflowStep.all
  end

  # GET /active_workflow_steps/1
  # GET /active_workflow_steps/1.json
  def show
  end

  # GET /active_workflow_steps/new
  def new
    @active_workflow_step = ActiveWorkflowStep.new
  end

  # GET /active_workflow_steps/1/edit
  def edit
  end

  # POST /active_workflow_steps
  # POST /active_workflow_steps.json
  def create
    @active_workflow_step = ActiveWorkflowStep.new(active_workflow_step_params)

    respond_to do |format|
      if @active_workflow_step.save
        format.html { redirect_to @active_workflow_step, notice: 'Active workflow step was successfully created.' }
        format.json { render :show, status: :created, location: @active_workflow_step }
      else
        format.html { render :new }
        format.json { render json: @active_workflow_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /active_workflow_steps/1
  # PATCH/PUT /active_workflow_steps/1.json
  def update
    respond_to do |format|
      if @active_workflow_step.update(active_workflow_step_params)
        format.html { redirect_to @active_workflow_step, notice: 'Active workflow step was successfully updated.' }
        format.json { render :show, status: :ok, location: @active_workflow_step }
      else
        format.html { render :edit }
        format.json { render json: @active_workflow_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /active_workflow_steps/1
  # DELETE /active_workflow_steps/1.json
  def destroy
    @active_workflow_step.destroy
    respond_to do |format|
      format.html { redirect_to active_workflow_steps_url, notice: 'Active workflow step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_active_workflow_step
      @active_workflow_step = ActiveWorkflowStep.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def active_workflow_step_params
      params.require(:active_workflow_step).permit(:number, :workflow_template_id, :active_workflow_id)
    end
end

app/helpers/active_workflow_steps_helper.rb
module ActiveWorkflowStepsHelper
end

app/views/active_workflow_steps/_form.html.erb
<%= form_for @active_workflow_step, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :number, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :number, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  active_workflow_steps_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/active_workflow_steps/edit.html.erb
<%- model_class = ActiveWorkflowStep -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => ActiveWorkflowStep %></h1>
</div>
<%= render :partial => 'form' %>

app/views/active_workflow_steps/index.html.erb
<%- model_class = ActiveWorkflowStep -%>
<div class="page-header">
  <h1><%=t '.title', :default => ActiveWorkflowStep %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:number) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @active_workflow_steps.each do |active_workflow_step| %>
      <tr>
        <td><%= active_workflow_step.id %></td>
        <td><%= active_workflow_step.number %></td>
        <td><%=l active_workflow_step.created_at, format: :long %></td>
        <td>
          <%= link_to active_workflow_step_path(active_workflow_step), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to active_workflow_step_path(active_workflow_step), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_active_workflow_step_path,
            :class => 'btn btn-primary' %>

app/views/active_workflow_steps/new.html.erb
<%- model_class = ActiveWorkflowStep -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => ActiveWorkflowStep %></h1>
</div>
<%= render :partial => 'form' %>

app/views/active_workflow_steps/show.html.erb
<%- model_class = ActiveWorkflowStep -%>
<div class="page-header">
  <h1><%=t '.title', :default => ActiveWorkflowStep %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:number) %></dt>
      <dd><pre class="prettyprint"><%= @active_workflow_step.number %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              active_workflow_steps_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_active_workflow_step_path(@active_workflow_step), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              active_workflow_step_path(@active_workflow_step),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>